version: '3.8'

services:
  postgres-ser-v2:
    image: postgres:15
    container_name: postgres-v2
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data

volumes:
  postgres_data_v2:
